### ISSUE TITLE
Doesn't work in projects that don't have coffee-script as a dependency.

### ISSUE THREAD

**Issue by conartist6** [Xiphe/karma-environments#8]
In a project which doesn't use coffee itself, karma-environments fails with the following message:

Error during loading "/{myProjectPath}/node_modules/karma-environments" plugin:
  /{myProjectPath}/node_modules/karma-environments/lib/index.coffee:2
  #* Define our framework factory
  ^
Unexpected token ILLEGAL
/{myProjectPath}/node_modules/karma/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
            ^
Error: No provider for "framework:environments"! (Resolving: framework:environments)
    at error (/{myProjectPath}/node_modules/karma/node_modules/di/lib/injector.js:22:68)
    at Object.parent.get (/{myProjectPath}/node_modules/karma/node_modules/di/lib/injector.js:9:13)
    at get (/{myProjectPath}/node_modules/karma/node_modules/di/lib/injector.js:54:19)
    at /{myProjectPath}/node_modules/karma/lib/server.js:29:14
    at Array.forEach (native)
    at start (/{myProjectPath}/node_modules/karma/lib/server.js:28:21)
    at invoke (/{myProjectPath}/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (/{myProjectPath}/node_modules/karma/lib/server.js:307:12)
    at Object.exports.run (/{myProjectPath}/node_modules/karma/lib/cli.js:220:27)
    at requireCliAndRun (/usr/local/lib/node_modules/karma-cli/bin/karma:44:16)

I worked around this by adding the coffee-script version specified in the karma-environments package.json to the project root level package.json.

My thoughts on possible fixes: coffee-script could be specified as a sibling dependency, a postinstall script could do coffee compilation using the already depended on compiler, or a compiled version of the source scripts could be checked in to the repo.

**Comment by Xiphe** [comment]
you're right. there should be a pure js version being build on npm `prepublish`.
I don't actively maintain this project anymore, feel welcome to send pr's or i can add you as contributor.
